repos:
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v2.4.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: [(feat|fix|docs|style|refactor|test|chore)(\(.+\))]
    - repo: local
      hooks:
        - id: pylint
          name: pylint
          entry: pylint tests/*
          language: system
          types: [ python ]
          args:
            [
              "-rn", # Only display messages
              "-sn", # Don't display the score
            ]
